def key_terminals(value: str):
    keys = {"!=": 1,
            "(": 2,
            ")": 3,
            "*": 4,
            "+": 5,
            ",": 6,
            "-": 7,
            "/": 8,
            ";": 9,
            "<": 10,
            "<=": 11,
            "=": 12,
            "==": 13,
            ">": 14,
            ">=": 15,
            "FLOAT": 16,
            "ID": 17,
            "INTEGER": 18,
            "STRING": 19,
            "[": 20,
            "]": 21,
            "else": 22,
            "float": 23,
            "if": 24,
            "int": 25,
            "read": 26,
            "return": 27,
            "string": 28,
            "void": 29,
            "while": 30,
            "write": 31,
            "{": 32,
            "}": 33,
            "$": 34,
            }
    
    return keys.get(value, keys[value] if value in keys else -1)
#     return keys[value]